name = "TPLSPEC"
grammar = "tplspec"
path_suffixes = ["tplspec"]
line_comments = ["# ", "## ", "#! "]
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "`", end = "`", close = true, newline = false, not_in = ["comment", "string"] },
]

auto_indent_using_last_non_empty_line = false
increase_indent_pattern = ":\\s*$"
